modLoader="javafml"
loaderVersion="[45,)"
license='MIT License'

[[mods]]
modId="modkit"
version="${file.jarVersion}"
displayName="ModKit"
credits=""
authors="TheDarkColour"
description='''
Make mods without all the boilerplate
'''
[[dependencies.modkit]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"
[[dependencies.modkit]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
