modLoader="javafml"
loaderVersion="[2,)"
license='MIT License'

[[mods]]
modId="modkit"
version="${file.jarVersion}"
displayName="ModKit"
credits=""
authors="TheDarkColour"
description='''
Data generation without all the boilerplate
'''
