/*
 * MIT License
 *
 * Copyright (c) 2026 thedarkcolour
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 */

package thedarkcolour.modkit.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import net.minecraft.client.data.models.model.ModelInstance;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;
import net.minecraft.world.level.ItemLike;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import thedarkcolour.modkit.MKUtils;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;

/**
 * Item model provider that uses vanilla's model generation utilities.
 * Provides the same API as the old NeoForge ItemModelProvider for easy migration.
 */
@SuppressWarnings({"UnusedReturnValue", "unused"})
public class MKItemModelProvider implements DataProvider {
    private final PackOutput output;
    private final String modid;
    private final Logger logger;
    private final boolean generate3dBlockItems;
    private final boolean generate2dItems;
    private final boolean generateSpawnEggs;
    @Nullable
    private final Consumer<MKItemModelProvider> addItemModels;

    private final Map<ResourceLocation, ModelInstance> models = new HashMap<>();
    private final Set<ResourceLocation> excluded = new HashSet<>();

    @ApiStatus.Internal
    public MKItemModelProvider(PackOutput output,
                               String modid,
                               Logger logger,
                               boolean generate3dBlockItems,
                               boolean generate2dItems,
                               boolean generateSpawnEggs,
                               @Nullable Consumer<MKItemModelProvider> addItemModels) {
        this.output = output;
        this.modid = modid;
        this.logger = logger;
        this.generate3dBlockItems = generate3dBlockItems;
        this.generate2dItems = generate2dItems;
        this.generateSpawnEggs = generateSpawnEggs;
        this.addItemModels = addItemModels;
    }

    /**
     * If any of {@link #generate2dItems}, {@link #generate3dBlockItems}, {@link #generateSpawnEggs} are true,
     * this method prevents the specified item from having a model generated.
     *
     * @param item Will have no models automatically generated by ModKit (can still add them in #addItemModels)
     */
    public void exclude(ItemLike item) {
        excluded.add(itemModelLocation(itemId(item)));
    }

    /**
     * Makes a 2d single layer item like hopper, gold ingot, or redstone dust item models
     */
    public void generic2d(ItemLike item) {
        generic2d(itemId(item));
    }

    /**
     * Makes a 2d single layer item like hopper, gold ingot, or redstone dust item models
     */
    public void generic2d(ResourceLocation itemId) {
        layer0(itemId, "item/generated");
    }

    /**
     * Makes a 2d single layer item with special transformations like the pickaxe or sword models.
     */
    public void handheld(ItemLike item) {
        handheld(itemId(item.asItem()));
    }

    /**
     * Makes a 2d single layer item with special transformations like the pickaxe or sword models.
     */
    public void handheld(ResourceLocation itemId) {
        layer0(itemId, "item/handheld");
    }

    /**
     * Creates a layer0 item model with the specified parent.
     */
    public void layer0(ResourceLocation itemId, String parentName) {
        ResourceLocation modelLoc = itemModelLocation(itemId);
        ResourceLocation texture = ResourceLocation.fromNamespaceAndPath(itemId.getNamespace(), "item/" + itemId.getPath());

        ModelInstance model = () -> {
            JsonObject json = new JsonObject();
            json.addProperty("parent", parentName);
            JsonObject textures = new JsonObject();
            textures.addProperty("layer0", texture.toString());
            json.add("textures", textures);
            return json;
        };

        this.models.put(modelLoc, model);
    }

    /**
     * Makes a 3d cube of a block for item model (references block model as parent)
     */
    public void generic3d(ItemLike item) {
        generic3d(itemId(item.asItem()));
    }

    /**
     * Makes a 3d cube of a block for item model (references block model as parent)
     */
    public void generic3d(ResourceLocation itemId) {
        ResourceLocation modelLoc = itemModelLocation(itemId);
        ResourceLocation parent = ResourceLocation.fromNamespaceAndPath(itemId.getNamespace(), "block/" + itemId.getPath());

        ModelInstance model = () -> {
            JsonObject json = new JsonObject();
            json.addProperty("parent", parent.toString());
            return json;
        };

        this.models.put(modelLoc, model);
    }

    /**
     * Creates a spawn egg item model.
     */
    public void spawnEgg(ItemLike item) {
        spawnEgg(itemId(item));
    }

    /**
     * Creates a spawn egg item model.
     */
    public void spawnEgg(ResourceLocation itemId) {
        ResourceLocation modelLoc = itemModelLocation(itemId);

        ModelInstance model = () -> {
            JsonObject json = new JsonObject();
            json.addProperty("parent", "item/template_spawn_egg");
            return json;
        };

        models.put(modelLoc, model);
    }

    /**
     * Creates a simple item model with the given parent.
     */
    public void withParent(ItemLike item, ResourceLocation parent) {
        withParent(itemId(item), parent);
    }

    /**
     * Creates a simple item model with the given parent.
     */
    public void withParent(ResourceLocation itemId, ResourceLocation parent) {
        ResourceLocation modelLoc = itemModelLocation(itemId);

        ModelInstance model = () -> {
            JsonObject json = new JsonObject();
            json.addProperty("parent", parent.toString());
            return json;
        };

        models.put(modelLoc, model);
    }

    private ResourceLocation itemModelLocation(ResourceLocation itemId) {
        return ResourceLocation.fromNamespaceAndPath(itemId.getNamespace(), "item/" + itemId.getPath());
    }

    public ResourceLocation itemId(ItemLike item) {
        if (BuiltInRegistries.ITEM.containsValue(item.asItem())) {
            return BuiltInRegistries.ITEM.getKey(item.asItem());
        } else {
            throw new IllegalStateException("Item " + item.asItem() + " does not exist in item registry");
        }
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        models.clear();
        excluded.clear();

        // Auto-generate models based on settings
        if (generate3dBlockItems || generate2dItems || generateSpawnEggs) {
            MKUtils.forModRegistry(Registries.ITEM, modid, (id, item) -> {
                if (generate3dBlockItems && item instanceof BlockItem) {
                    generic3d(id);
                } else if (generateSpawnEggs && item instanceof SpawnEggItem) {
                    spawnEgg(id);
                } else if (generate2dItems) {
                    // todo check if item is in "swords" tag, "pickaxes" tag, etc.
                    // kind of a downgrade due to SwordItem and PickaxeItem no longer existing
                    if (item instanceof ShovelItem
                            || (item.getDescriptionId().contains("sword") && item.components().has(DataComponents.TOOL))
                            || item instanceof HoeItem
                            || item instanceof AxeItem
                            || (item.getDescriptionId().contains("pick") && item.components().has(DataComponents.TOOL))
                    ) {
                        this.logger.info("Detected item {} as a handheld, autogenerating handheld model (this can be manually overridden)", item.builtInRegistryHolder().key().location());
                        handheld(id);
                    } else {
                        generic2d(id);
                    }
                }
            });
        }

        // Run user-provided model additions
        if (addItemModels != null) {
            addItemModels.accept(this);
        }

        // Remove excluded models
        for (ResourceLocation exclusion : excluded) {
            models.remove(exclusion);
        }

        // Save all models
        Path basePath = output.getOutputFolder(PackOutput.Target.RESOURCE_PACK);
        CompletableFuture<?>[] futures = new CompletableFuture<?>[models.size()];
        int i = 0;

        for (var entry : models.entrySet()) {
            ResourceLocation modelLoc = entry.getKey();
            Path outputPath = basePath.resolve(modelLoc.getNamespace())
                    .resolve("models")
                    .resolve(modelLoc.getPath() + ".json");
            JsonElement json = entry.getValue().get();
            futures[i++] = DataProvider.saveStable(cache, json, outputPath);
        }

        return CompletableFuture.allOf(futures);
    }

    @Override
    public String getName() {
        return "ModKit Item Models for mod '" + this.modid + "'";
    }
}
